#### GENERAL ####

# this is the desired analysis sampleRate, not that of the file
# if the file has a different sampleRate, it will be resampled
# to have the same sampleRate as specified here.
analysisSampleRate: 44100

# compute the audio file from start time to end time (in seconds)
startTime: 0.0
endTime: 2000.0

# whether to apply equal loudness contour (filter): yes|no|both
equalLoudness: true
nequalLoudness: true
shortSound: false # set to true when analyzing a sample less than 2s

# change to true when svm models are trained
svm:
    compute: false

segmentation:
    compute: false
    cpw: 5
    size1: 1000
    inc1: 300
    size2: 600
    inc2: 50
    minimumSegmentsLength: 10.0 # seconds

# to be added:
# downmix: 'mix'
#### OPTIONS SPECIFIC TO EACH EXTRACTOR ####

# low-level extractor options (barkbands_kurtosis, barkbands_skewness,
#                              barkbands_spread, dissonance, hfc,
#                              pitch, pitch_instantaneous_confidence, pitch_salience,
#                              silence_rate_20dB, silence_rate_30dB, silence_rate_60dB,
#                              spectral_centroid, spectral_complexity,
#                              spectral_crest, spectral_decrease,
#                              spectral_energy, spectral_energyband_high,
#                              spectral_energyband_low,
#                              spectral_energyband_middle_high,
#                              spectral_energyband_middle_low,
#                              spectral_flatness_db, spectral_flux, spectral_kurtosis,
#                              spectral_rms, spectral_rolloff, spectral_skewness,
#                              spectral_spread, spectral_strongpeak, zerocrossingrate,
#                              barkbands, mfcc, spectral_contrast)
lowlevel:
    compute: true
    frameSize: 2048
    hopSize:   1024
    zeroPadding:  0
    silentFrames: 'noise'
    windowType:  'blackmanharris62'
    stats: [ "mean", "var", "min", "max", "dmean", "dmean2", "dvar", "dvar2" ]
    mfccStats: [ "mean", "cov", "icov" ]

# average loudness options (average_loudness)
average_loudness:
    compute: true
    frameSize: 88200
    hopSize:   44100

# tempotap extractor options (beats_loudness, beats_loudness_bass,
#                             bpm, bpm_confidence,
#                             first_peak_bpm, first_peak_spread, first_peak_weight,
#                             onset_rate, second_peak_bpm,
#                             second_peak_spread, second_peak_weight,
#                             beats_position, bpm_estimates, bpm_intervals,
#                             onset_times, rubato_start, rubato_stop, perceptual_tempo)
rhythm:
    compute: true
    # whether or not to use onsets as periodicity function
    useOnset: true
    # whether or not to use energy bands as periodicity function
    useBands: true

    # sizes of frames. Note that frameNumber*hopSize ~= about 6 seconds
    numberFrames: 1024
    hopSize:      256
    frameSize:   1024
    frameHop:    1024
    stats: [ "mean", "var", "min", "max", "dmean", "dmean2", "dvar", "dvar2" ]

# tonal extractor options (chords_changes_rate, chords_number_rate,
#                          chords_strength, key_strength,
#                          tuning_frequency, hpcp, chords_key,
#                          tuning_diatonic_strength,
#                          tuning_equal_tempered_deviation,
#                          tuning_nontempered_energy_ratio,
#                          chords_scale, key_key, key_scale)
tonal:
    compute: true
    frameSize:   4096
    hopSize:     2048
    zeroPadding:    0
    silentFrames: 'noise'
    windowType:  'blackmanharris62'
    stats: [ "mean", "var", "min", "max", "dmean", "dmean2", "dvar", "dvar2" ]

sfx: # pitch_max_to_total, pitch_min_to_total, pitch_centroid,
     # pitch_after_max_before_max_energy_ratio,
    compute: true
    stats: [ "mean", "var", "min", "max", "dmean", "dmean2", "dvar", "dvar2" ]

# sfx not available at the moment...
# (temporal_decrease, temporal_kurtosis, temporal_skewness
#  temporal_spread, temporal_centroid, effective_duration,
#  logattacktime, strong_decay, flatness,
#  max_to_total, tc_to_total,
#  der_av_after_max, max_der_befor_max)

panning:
    compute: false
    frameSize: 8192
    hopSize: 2048
    zeropadding: 8192
    silentFrames: 'noise'
    windowType: 'hann'
    stats: [ 'copy' ]
